SELECT b.USER_ID, b.NICKNAME,
CONCAT(b.CITY,' ',b.STREET_ADDRESS1,' ',STREET_ADDRESS2) 전체주소,
CONCAT(LEFT(B.TLNO,3),'-',(MID(B.TLNO,4,4)),'-',(RIGHT(B.TLNO,4)))
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_USER b
ON a.WRITER_ID = b.USER_ID
GROUP BY b.USER_ID
HAVING COUNT(*) >= 3
ORDER BY b.USER_ID DESC;