SELECT a.PRODUCT_ID, a.PRODUCT_NAME, 
SUM(AMOUNT) * a.PRICE AS TOTAL_SALES
FROM FOOD_ORDER b 
JOIN FOOD_PRODUCT a
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05"
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;